compatibility_flags = [ "nodejs_compat" ]

name = "jelvintours"
main = "api/index.js" 
compatibility_date = "2025-05-20"


[vars]
FIREBASE_PROJECT_ID = "jelvintour"
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-xcpxg@jelvintour.iam.gserviceaccount.com"
FIREBASE_PRIVATE_KEY ="-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCX3y9b9PK+vFUs\nKpNKcUO6WXaoaK9JHMhXmojwo0TEpdPX7TOI7UB0kRwB+qCjh4ege57rxsRwCgwa\n3u+ci7oeXWk5OMAlMmS/PRHk9/M51BsnBu8yQfscFFrSYhxrStrIdKpfw9LX1Mat\nDWCLIL5oGVAVdqRsFlj8cXcQGnKZNmEu98/XLqhJCgkKPRtSVDbQWnpHYMjaK+1P\n2Bg/sfF5M2FQmw4JjTSQ0bbaP0z8gB5m0+A0oTrOfwLAABOpTX879hfyXQjfOXCm\nBtN9Ipf0fU2bjtNDxPGGtIbYjF4ifNkMTB9aH7QbG3Dnm5kMKJUh8w/q01ixC269\nFNT622ddAgMBAAECggEAHS6GolgDA7ja8dFde26fmbFCjlINKlKEQWcBfKGWn2WQ\nutsKbbtOyQcv90Zh8wIiAql2TC4lhTS9BjXDm1Qy505CH3ti2lLgTmnM5C7rlrdF\nn15i/Eh22Hqlx+qPtOMNfnqCWUPeodex9EMPg7Q/Oe/xNiqVpeo2X41q2BaI4hzn\nnth6U9mxGHKxwBaxjhLh2yiz7zI9eioQ576oy2A8qsz5HGBEFkcleX/qYth//yOI\nWhCJf/zXXu6SlFVoCxcOY/knQrcYOVy5cnOH7RGsHEYYNlNSRQOczOxO2E7J9oCX\n06iFMGLwuME6vlYzbm8Ixs11ZhSlrIk3+9vUNWU32QKBgQDT9WHY9StFBfM3rn4U\nxYHpL+OnTQodBeAlKRWantnfYmpNbIol60urGOxlvEZxK5KxO0bFqe4TilVm1WMf\nFlGkA3ij6LIPYXBgDrkvpB7CBzTUhvZd6RjKclNfwAVspatcAZ/zy606vpkL46gZ\ngB/0PvHecYhGnT2KsRKc/Sy+lQKBgQC3baL4tf1z5g1LbeGFcHLHJ1eCn7UnC9bo\neTlAvJZtS4WCrX1mKxGcZuhsqbEPLMdxDQ9JA4TsNFpJd+f3piWolx3GQGWbjmfR\nrxgLcWz+pwGQrdyIo8X/9zCQz2aB+emjS8o5jhGFqV/451Qu7x+xVM1w+JvWmHl6\niXlPhcB7qQKBgFvw+PyvfJF4P0RMAIzqD6wjBdEwbc6hGdWEuMZVWZS4j/v9tP81\nzaDuMrz+ql+00vDmEZD0YT1AqELvFQwLFmbayp3u9i4Nyj0gpduwiVcI4TW/RWb/\nEa3fYaMLHE9AndBPNB8Anqf4vVKW8ff9x96e3zPqc36N/oAGx1gpyhrxAoGAO4U2\nBuJ3Fe6mjb1gGr68X+diPB6616q9173OWDVZ0qlY72iAcnCzTD8QWIJP1A7BwOtt\n9FFSBpuOWJyyBuhA/A3dOYGX9vwksCPS95OcvJ1QorPoBeauzzpU5giGyNJhf/2N\n51M0WFz3qXrXFEu/yvkrmObzGpVrhdmqJaXPKdECgYBbR/m0FVUPUS5xojztOaeE\nQ80D3G/KvV5grN4/7k93VePmu8WdZI1+kGlswLLzcMt5TFWoyKtzaKjKZYcf14UO\nMpBlU9du8f/H2wssm28eeRYwSE9bF7CLCSNBcdrnwUETT4ZHxXVxvuIJ52cyP2Gm\n4agznlaUeJIFV0+/0Gv6NQ==\n-----END PRIVATE KEY-----\n"
DATABASE_URL = "postgresql://traveltours_owner:BaZU9hmKqH8k@ep-cold-base-a53m37xe.us-east-2.aws.neon.tech/traveltours?sslmode=require"


[build]
command = "npm run build" # Optional: Build command for your app

workers_dev = true
# Enable development mode

[account]
id = "35be2a836c405cc11127292d19a0cee5" # Replace with your Cloudflare account ID

